<?php
require_once('php/task.php');
$mathematics = new Task ('Lorem ipsum dolor sit amet, consectetur adipisicing elit. A odit explicabo fugit ea numquam porro ex maiores tempore pariatur est, quo enim, culpa quibusdam fuga. Quo provident, molestiae atque voluptatem. Harum enim ea nesciunt voluptate nostrum libero mollitia aliquam, quod voluptatem minus eveniet doloribus facilis error soluta quisquam, sed facere.', 5, 'Математика');
$history = new Task ('Lorem ipsum dolor sit amet, consectetur adipisicing elit. A odit explicabo fugit ea numquam porro ex maiores tempore pariatur est, quo enim, culpa quibusdam fuga. Quo provident, molestiae atque voluptatem. Harum enim ea nesciunt voluptate nostrum libero mollitia aliquam, quod voluptatem minus eveniet doloribus facilis error soluta quisquam, sed facere.', 4, 'История');
$Informatics = new Task ('Lorem ipsum dolor sit amet, consectetur adipisicing elit. A odit explicabo fugit ea numquam porro ex maiores tempore pariatur est, quo enim, culpa quibusdam fuga. Quo provident, molestiae atque voluptatem. Harum enim ea nesciunt voluptate nostrum libero mollitia aliquam, quod voluptatem minus eveniet doloribus facilis error soluta quisquam, sed facere.', 3, 'Информатика');
$geography = new Task ('Lorem ipsum dolor sit amet, consectetur adipisicing elit. A odit explicabo fugit ea numquam porro ex maiores tempore pariatur est, quo enim, culpa quibusdam fuga. Quo provident, molestiae atque voluptatem. Harum enim ea nesciunt voluptate nostrum libero mollitia aliquam, quod voluptatem minus eveniet doloribus facilis error soluta quisquam, sed facere.', 2, 'География');
$astronomy = new Task ('Lorem ipsum dolor sit amet, consectetur adipisicing elit. A odit explicabo fugit ea numquam porro ex maiores tempore pariatur est, quo enim, culpa quibusdam fuga. Quo provident, molestiae atque voluptatem. Harum enim ea nesciunt voluptate nostrum libero mollitia aliquam, quod voluptatem minus eveniet doloribus facilis error soluta quisquam, sed facere.', 1, 'Астрономия');
$scienceTest = [];
array_push($scienceTest, $mathematics, $history, $Informatics, $geography, $astronomy);
